# Generated by Django 5.2.7 on 2025-10-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_notifications_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_avatar',
            field=models.CharField(blank=True, choices=[('default1', 'Монеты'), ('default2', 'График'), ('default3', 'Копилка'), ('default4', 'Драгоценность')], max_length=20, null=True),
        ),
    ]
