# Generated by Django 5.2.7 on 2025-10-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_default_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_avatar',
            field=models.CharField(blank=True, choices=[('default1', 'Золотой инвестор'), ('default2', 'Аналитик'), ('default3', 'Бережливая свинка'), ('default4', 'Финансовый магнат')], max_length=20, null=True),
        ),
    ]
