# Generated by Django 5.2.7 on 2025-10-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_default_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_border',
            field=models.CharField(choices=[('novice', 'Новичок'), ('beginner', 'Ученик'), ('intermediate', 'Защитник'), ('advanced', 'Эксперт'), ('expert', 'Мастер'), ('master', 'Гуру'), ('legend', 'Легенда')], default='novice', max_length=20),
        ),
    ]
