# Generated by Django 5.2.7 on 2025-10-28 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_avatar_border'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_avatar',
            field=models.CharField(blank=True, choices=[('default1', 'Мечтатель'), ('default2', 'Новатор'), ('default3', 'Аналитик'), ('default4', 'Победитель')], max_length=20, null=True),
        ),
    ]
