# Generated by Django 5.2.7 on 2025-10-12 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_streak_notification_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='type',
            field=models.CharField(choices=[('quiz', 'Викторина'), ('quest', 'Квест'), ('simulation', 'Симуляция'), ('sorting', 'Сортировка')], default='quiz', max_length=20),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.topic')),
            ],
        ),
    ]
