# Generated by Django 5.2.7 on 2025-10-12 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_level_type_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='text',
            new_name='message',
        ),
    ]
