# Generated by Django 5.2.7 on 2025-10-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_rename_text_notification_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='avatars/items/')),
                ('cost_coins', models.IntegerField(default=20)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='message',
            new_name='text',
        ),
    ]
