# Generated by Django 4.2.6 on 2025-10-17 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0007_userlevelprogress_best_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('total_coins', models.IntegerField(default=0)),
                ('levels_completed', models.IntegerField(default=0)),
                ('achievements_count', models.IntegerField(default=0)),
                ('streak_days', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entry', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_points', '-levels_completed', '-achievements_count'],
            },
        ),
    ]
