# Generated by Django 4.2.6 on 2025-10-17 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0009_auto_20251017_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='content',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='level',
            name='type',
            field=models.CharField(choices=[('quiz', 'Викторина'), ('scenario', 'Сценарий'), ('calculation', 'Расчеты'), ('matching', 'Сопоставление'), ('sorting', 'Сортировка'), ('simulation', 'Симуляция'), ('quest', 'Квест')], default='quiz', max_length=20),
        ),
        migrations.AlterField(
            model_name='streak',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
