# Generated by Django 5.2.7 on 2025-10-21 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_alter_level_type'),
        ('game', '0012_improved_level_types'),
    ]

    operations = [
    ]
