# Generated by Django 5.2.7 on 2025-10-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_merge_0012_alter_level_type_0012_improved_level_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['main_category', 'order_in_category']},
        ),
        migrations.AddField(
            model_name='achievement',
            name='category',
            field=models.CharField(choices=[('progress', 'Прогресс'), ('streak', 'Серии'), ('points', 'Очки'), ('coins', 'Монеты'), ('levels', 'Уровни'), ('special', 'Особые')], default='progress', max_length=20),
        ),
        migrations.AddField(
            model_name='achievement',
            name='coins_reward',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='achievement',
            name='icon',
            field=models.CharField(default='fa-trophy', max_length=50),
        ),
        migrations.AddField(
            model_name='achievement',
            name='points_reward',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='achievement',
            name='rarity',
            field=models.CharField(choices=[('common', 'Обычная'), ('uncommon', 'Необычная'), ('rare', 'Редкая'), ('legendary', 'Легендарная')], default='common', max_length=20),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='main_category',
            field=models.CharField(choices=[('basics', 'Основы финансов'), ('security', 'Безопасность'), ('investments', 'Инвестиции'), ('planning', 'Планирование')], default='basics', max_length=20),
        ),
        migrations.AddField(
            model_name='topic',
            name='order_in_category',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
