# Generated by Django 5.2.7 on 2025-10-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_alter_topic_options_achievement_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leveloption',
            options={'ordering': ['question_number', 'order']},
        ),
        migrations.AddField(
            model_name='leveloption',
            name='hint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leveloption',
            name='question_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
