# Generated by Django 5.2.7 on 2025-10-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_alter_leveloption_options_leveloption_hint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlevelprogress',
            name='best_time',
            field=models.IntegerField(default=0, help_text='Лучшее время прохождения в секундах'),
        ),
        migrations.AddField(
            model_name='userlevelprogress',
            name='completion_time',
            field=models.IntegerField(default=0, help_text='Время прохождения в секундах'),
        ),
    ]
