# Generated by Django 5.2.7 on 2025-10-25 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_userlevelprogress_best_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_subcategory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.topic'),
        ),
    ]
